# APQ8064
obj-$(CONFIG_ARCH_APQ8064)	+= gcc-msm8960.o
obj-$(CONFIG_ARCH_APQ8064)	+= clk-pll.o
obj-$(CONFIG_ARCH_APQ8064)	+= clk-rcg.o
obj-$(CONFIG_ARCH_APQ8064)	+= clk-branch.o
obj-$(CONFIG_ARCH_APQ8064)	+= clk-regmap.o
obj-$(CONFIG_ARCH_APQ8064)	+= common.o
obj-$(CONFIG_ARCH_APQ8064)	+= reset.o
obj-$(CONFIG_ARCH_APQ8064)	+= clock.o

obj-y				+= gdsc.o
obj-y				+= mdss/
